version: '3.8'

x-omnistrate-integrations:
  - omnistrateLogging:
  - omnistrateMetrics:

x-omnistrate-service-plan:
  name: 'clazar-exporter'
  tenancyType: 'OMNISTRATE_DEDICATED_TENANCY'
  
services:
  metering-processor:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    platform: linux/amd64
    env_file:
      - .env
    # environment:
    #   S3_BUCKET_NAME: $var.s3BucketName
    #   SERVICE_NAME: $var.serviceName
    #   ENVIRONMENT_TYPE: $var.environmentType
    #   PLAN_ID: $var.planId
    #   CLAZAR_CLIENT_ID: $var.clazarClientId
    #   CLAZAR_CLIENT_SECRET: $var.clazarClientSecret
    #   CLAZAR_CLOUD: $var.clazarCloud
    #   AWS_ACCESS_KEY_ID: $var.awsAccessKeyId
    #   AWS_SECRET_ACCESS_KEY: $var.awsSecretAccessKey
    #   AWS_REGION: $var.awsRegion
    #   CLAZAR_API_URL: $var.clazarApiUrl
    #   STATE_FILE_PATH: $var.stateFilePath
    #   MAX_MONTHS_PER_RUN: $var.maxMonthsPerRun
    #   DRY_RUN: $var.dryRun
    x-omnistrate-compute:
      replicaCount: 1
      instanceTypes:
        - cloudProvider: aws
          name: t4g.small
        - cloudProvider: gcp
          name: e2-small
        - cloudProvider: azure
          name: Standard_B1s
    x-omnistrate-job-config:
      backoffLimit: 0
      activeDeadlineSeconds: 3600
    x-omnistrate-api-params:
      - key: s3BucketName
        description: The name of the S3 bucket to pull usage data from.
        name: S3 Bucket Name
        type: String
        modifiable: true
        required: true
        export: true
      - key: serviceName
        description: Service Name
        name: Service Name
        type: String
        modifiable: true
        required: true
        export: true
      - key: environmentType
        description: Environment Type
        name: Environment Type
        type: String
        modifiable: true
        required: true
        export: true
      - key: planId
        description: Plan ID
        name: Plan ID
        type: String
        modifiable: true
        required: true
        export: true
      - key: clazarClientId
        description: Clazar Client ID
        name: Clazar Client ID
        type: Secret
        modifiable: true
        required: true
        export: false
      - key: clazarClientSecret
        description: Clazar Client Secret
        name: Clazar Client Secret
        type: Secret
        modifiable: true
        required: true
        export: false
      - key: clazarCloud
        description: Clazar Cloud
        name: Clazar Cloud
        type: String
        modifiable: true
        required: true
        export: true
        options:
          - aws
          - gcp
          - azure
      - key: awsAccessKeyId
        description: AWS Access Key ID
        name: AWS Access Key ID
        type: String
        modifiable: true
        required: true
        export: false
      - key: awsSecretAccessKey
        description: AWS Secret Access Key
        name: AWS Secret Access Key
        type: String
        modifiable: true
        required: true
        export: false
      - key: awsRegion
        description: AWS Region
        name: AWS Region
        type: String
        modifiable: true
        required: false
        export: true
        defaultValue: "us-east-1"
      - key: clazarApiUrl
        description: Clazar API URL
        name: Clazar API URL
        type: String
        modifiable: true
        required: false
        export: true
        defaultValue: "https://api.clazar.io/metering/"
      - key: stateFilePath
        description: State File Path in the S3 bucket
        name: State File Path
        type: String
        modifiable: true 
        required: false
        export: true
        defaultValue: "metering_state.json"
      - key: maxMonthsPerRun
        description: Maximum Months to Process Per Run
        name: Max Months Per Run
        type: Float64
        modifiable: true
        required: false
        export: true
        defaultValue: "12"
      - key: dryRun
        description: Dry Run Mode (true/false)
        name: Dry Run Mode
        type: Boolean
        modifiable: true
        required: false
        export: true
        defaultValue: "false"
    x-omnistrate-mode-internal: false
# x-omnistrate-image-registry-attributes:
#   ghcr.io:
#     auth:
#       password: ${{ secrets.GitHubPAT }}
#       username: G-Despacito
