version: '3.8'

x-customer-integrations:
  logs: 
  metrics: 

x-omnistrate-service-plan:
  name: 'clazar-exporter'
  tenancyType: 'OMNISTRATE_DEDICATED_TENANCY'
  ## TODO : Replace <AWS_ACCOUNT_ID> with your account id and uncomment the hostedDeployment section below
  # hostedDeployment:
  #   awsAccountId: "<AWS_ACCOUNT_ID>"
  #   awsBootstrapRoleAccountArn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/omnistrate-bootstrap-role
  
services:
  metering-processor:
    image: ghcr.io/omnistrateio/usage-export-clazar-recipe:0.0.1
    privileged: true
    platform: linux/amd64
    ports:
      - 8080 # health check port
    environment:
      SERVICE_NAME: $var.serviceName
      ENVIRONMENT_TYPE: $var.environmentType
      PLAN_ID: $var.planId
      CLAZAR_CLIENT_ID: $var.clazarClientId
      CLAZAR_CLIENT_SECRET: $var.clazarClientSecret
      CLAZAR_CLOUD: $var.clazarCloud
      AWS_S3_BUCKET_NAME: $var.awsS3BucketName
      AWS_REGION: $var.awsRegion
      AWS_ACCESS_KEY_ID: $var.awsAccessKeyId
      AWS_SECRET_ACCESS_KEY: $var.awsSecretAccessKey
      DIMENSION1_NAME: $var.dimension1Name
      DIMENSION1_FORMULA: $var.dimension1Formula
      DIMENSION2_NAME: $var.dimension2Name
      DIMENSION2_FORMULA: $var.dimension2Formula
      DIMENSION3_NAME: $var.dimension3Name
      DIMENSION3_FORMULA: $var.dimension3Formula
      START_MONTH: $var.startMonth
      DRY_RUN: $var.dryRun
      LOG_LEVEL: $var.logLevel
    x-omnistrate-compute:
      replicaCount: 1
      instanceTypes:
        - cloudProvider: aws
          name: t3a.small
        - cloudProvider: gcp
          name: e2-small
        - cloudProvider: azure
          name: Standard_B1s
    x-omnistrate-api-params:
      - key: serviceName
        description: Service Name
        name: Service Name
        type: String
        modifiable: true
        required: true
        export: true
      - key: environmentType
        description: Environment Type (e.g. PROD)
        name: Environment Type
        type: String
        modifiable: true
        required: true
        export: true
      - key: planId
        description: Plan ID
        name: Plan ID
        type: String
        modifiable: true
        required: true
        export: true
      - key: clazarClientId
        description: Clazar Client ID
        name: Clazar Client ID
        type: Password
        modifiable: true
        required: true
        export: false
      - key: clazarClientSecret
        description: Clazar Client Secret
        name: Clazar Client Secret
        type: Password
        modifiable: true
        required: true
        export: false
      - key: clazarCloud
        description: Clazar Cloud
        name: Clazar Cloud
        type: String
        modifiable: true
        required: true
        export: true
        options:
          - aws
          - gcp
          - azure
      - key: awsAccessKeyId
        description: AWS Access Key ID
        name: AWS Access Key ID
        type: String
        modifiable: true
        required: true
        export: false
      - key: awsSecretAccessKey
        description: AWS Secret Access Key
        name: AWS Secret Access Key
        type: String
        modifiable: true
        required: true
        export: false
      - key: awsS3BucketName
        description: The name of the S3 bucket to pull usage data from.
        name: AWS S3 Bucket Name
        type: String
        modifiable: true
        required: true
        export: true
      - key: awsRegion
        description: AWS Region
        name: AWS Region
        type: String
        modifiable: true
        required: false
        export: true
        defaultValue: "us-west-2"
      - key: dimension1Name
        description: Custom Dimension 1 Name
        name: Custom Dimension 1 Name
        type: String
        modifiable: true
        required: true
        export: true
      - key: dimension1Formula
        description: Custom Dimension 1 Formula (e.g., cpu_core_hours / 2)
        name: Custom Dimension 1 Formula
        type: String
        modifiable: true
        required: true
        export: true
      - key: dimension2Name
        description: Custom Dimension 2 Name
        name: Custom Dimension 2 Name
        type: String
        modifiable: true
        required: false
        export: true
      - key: dimension2Formula
        description: Custom Dimension 2 Formula (e.g., memory_byte_hours * 2)
        name: Custom Dimension 2 Formula
        type: String
        modifiable: true
        required: false
        export: true
      - key: dimension3Name
        description: Custom Dimension 3 Name
        name: Custom Dimension 3 Name
        type: String
        modifiable: true
        required: false
        export: true
      - key: dimension3Formula
        description: Custom Dimension 3 Formula (e.g., storage_allocated_byte_hours + cpu_core_hours)
        name: Custom Dimension 3 Formula
        type: String
        modifiable: true
        required: false
        export: true
      - key: startMonth
        description: "Start Month for processing (format: YYYY-MM)"
        name: Start Month
        type: String
        modifiable: true
        required: true
        export: true
      - key: dryRun
        description: Enable dry run mode to test without actual data sending to Clazar.
        name: Dry Run Mode
        type: Boolean
        modifiable: true
        required: false
        export: true
        defaultValue: "false"
      - key: logLevel
        description: Logging level (e.g., INFO, DEBUG)
        name: Log Level
        type: String
        modifiable: true
        required: false
        export: true
        defaultValue: "INFO"
        options:
          - INFO
          - DEBUG
          - WARNING
          - ERROR
    x-omnistrate-mode-internal: false
